### ISSUE TITLE
Ns in locus flank

### ISSUE THREAD

**Issue by hdashnow** [broadinstitute/tandem-repeat-catalogs#2]
I was testing this catalog with ExpansionHunter and came across the following error message:

```
2024-09-06T16:55:43,[Initializing reference /pl/active/dashnowlab/data/ref-genomes/human_GRCh38_no_alt_analysis_set.fasta]
2024-09-06T16:55:43,[Loading variant catalog from disk /pl/active/dashnowlab/data/TRcatalogs/broad-tandem-repeat-catalog-release_v0.9/repeat_catalog.3x_and_9bp.hg38.merged_and_annotated.json]
2024-09-06T16:56:25,[Error loading locus 1-10001-10108-TAACCC: Flanks can contain at most 5 characters N but found 1000 Ns]
```

Ref used: https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-pigeon_ref_sets/Human_hg38_Gencode_v39/human_GRCh38_no_alt_analysis_set.fasta

If you haven't come across this, perhaps this is specific to the reference genome? Which one did you test the catalog with?

**Comment by hdashnow** [comment]
I just replicated it with the Broad resource bundle version from here: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0

```
2024-09-06T17:12:04,[Initializing reference /pl/active/dashnowlab/data/ref-genomes/GATK-resource-bundle/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta]
2024-09-06T17:12:04,[Loading variant catalog from disk /pl/active/dashnowlab/data/TRcatalogs/broad-tandem-repeat-catalog-release_v0.9/repeat_catalog.3x_and_9bp.hg38.merged_and_annotated.json]
2024-09-06T17:12:46,[Error loading locus 1-10001-10108-TAACCC: Flanks can contain at most 5 characters N but found 1000 Ns]
```

**Comment by bw2** [comment]
Thanks for reporting this! I use https://github.com/bw2/ExpansionHunter which converts this error to a warning. 
We could either exclude these loci from the EH version of the catalog, or ask people to use one of these forks:
https://github.com/bw2/ExpansionHunter or 
https://gitlab.com/andreassh/ExpansionHunter

**Comment by bw2** [comment]
I will remove the 3,746 loci that trigger this error from the .EH.json version of the catalog by running this script
https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/filter_out_loci_with_Ns_in_flanks_from_expansion_hunter_catalog.py

**Comment by hdashnow** [comment]
Wonderful, thank you! Do you think it makes sense to run one of those forks for all projects in general? I see they have difference changes, are there key differences? Are they kept up to date with changes? I know the original isn't being actively maintained these days, but not sure if that is likely to change.

**Comment by bw2** [comment]
I use my own fork of ExpansionHunter because of the added conveniences (ie. warnings instead of errors, ability to load gzipped catalogs, genotype a specific locus from the catalog, etc.) and optimizations for seeking mode. Same thing for [REViewer](https://github.com/bw2/REviewer). In my tests, the output was always identical, so I use it for all my projects.

**Comment by bw2** [comment]
Also, the EH catalog has been updated to remove the N-error loci.

**Comment by hdashnow** [comment]
@bw2 could you please add the updated files without N-error loci? We want to test it specifically with the original ExpansionHunter for a reviewer request for another paper.

**Comment by bw2** [comment]
@hdashnow  the [repeat_catalog_v1.hg38.1_to_1000bp_motifs.EH.json.gz](https://github.com/broadinstitute/tandem-repeat-catalog/releases/tag/v1.0) already excludes the N-error loci identified by "[filter_out_loci_with_Ns_in_flanks_from_expansion_hunter_catalog.py](https://github.com/broadinstitute/str-analysis/blob/main/str_analysis/filter_out_loci_with_Ns_in_flanks_from_expansion_hunter_catalog.py)". 
Are you still seeing this error?
